using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atelier_backend.Migrations;

public partial class AddFabric : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS "Fabrics" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "Name" text NOT NULL,
                "Category" text NULL,
                "Description" text NULL,
                "Price" numeric(10,2) NOT NULL,
                "Color" text NULL,
                "AvailableQuantity" numeric(10,2) NOT NULL,
                "ImageUrl" text NULL,
                "IsActive" boolean NOT NULL,
                CONSTRAINT "PK_Fabrics" PRIMARY KEY ("Id")
            );
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "Fabrics");
    }
}
